name: CodSpeed
'on':
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
permissions:
  contents: read
  id-token: write
jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Get pnpm store directory
      shell: bash
      run: 'echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

        '
    - name: Setup pnpm cache
      uses: actions/cache@v5
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: '${{ runner.os }}-pnpm-store-

          '
    - name: Install dependencies
      run: COREPACK_ENABLE_STRICT=0 pnpm install --no-frozen-lockfile
    - name: Run benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        upload-url: ${{ secrets.CODSPEED_FRANCOIS_DEV_UPLOAD_URL }}
        mode: simulation
        run: npx vitest bench --run
